Importing Libraries

In [1]:
import pandas as pd
import numpy as np

Loading the data and merging it

In [2]:
training_transx = pd.read_csv(r"D:\Fraud-Detection\data\raw\train_transaction.csv")
training_id = pd.read_csv(r"D:\Fraud-Detection\data\raw\train_identity.csv")
df = training_transx.merge(training_id , on  = 'TransactionID' , how = 'left')

In [3]:
df

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.50,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.00,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.00,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.00,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.00,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,3577535,0,15811047,49.00,W,6550,NaN,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590536,3577536,0,15811049,39.50,W,10444,225.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590537,3577537,0,15811079,30.95,W,12037,595.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590538,3577538,0,15811088,117.00,W,7826,481.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590539,3577539,0,15811131,279.95,W,15066,170.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Sorting by time

In [4]:
df = df.sort_values('TransactionDT').reset_index(drop = True)

Removing columns with more thamn 50 percent missing values

In [5]:
df

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.50,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.00,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.00,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.00,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.00,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,3577535,0,15811047,49.00,W,6550,NaN,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590536,3577536,0,15811049,39.50,W,10444,225.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590537,3577537,0,15811079,30.95,W,12037,595.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590538,3577538,0,15811088,117.00,W,7826,481.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590539,3577539,0,15811131,279.95,W,15066,170.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
missing_rate = df.isnull().mean()
missing_rate

TransactionID     0.000000
isFraud           0.000000
TransactionDT     0.000000
TransactionAmt    0.000000
ProductCD         0.000000
                    ...
id_36             0.761261
id_37             0.761261
id_38             0.761261
DeviceType        0.761557
DeviceInfo        0.799055
Length: 434, dtype: float64

In [7]:
columns_drop = missing_rate[missing_rate > 0.5].index.tolist()
columns_drop

['dist1',
 'dist2',
 'R_emaildomain',
 'D5',
 'D6',
 'D7',
 'D8',
 'D9',
 'D12',
 'D13',
 'D14',
 'M5',
 'M7',
 'M8',
 'M9',
 'V138',
 'V139',
 'V140',
 'V141',
 'V142',
 'V143',
 'V144',
 'V145',
 'V146',
 'V147',
 'V148',
 'V149',
 'V150',
 'V151',
 'V152',
 'V153',
 'V154',
 'V155',
 'V156',
 'V157',
 'V158',
 'V159',
 'V160',
 'V161',
 'V162',
 'V163',
 'V164',
 'V165',
 'V166',
 'V167',
 'V168',
 'V169',
 'V170',
 'V171',
 'V172',
 'V173',
 'V174',
 'V175',
 'V176',
 'V177',
 'V178',
 'V179',
 'V180',
 'V181',
 'V182',
 'V183',
 'V184',
 'V185',
 'V186',
 'V187',
 'V188',
 'V189',
 'V190',
 'V191',
 'V192',
 'V193',
 'V194',
 'V195',
 'V196',
 'V197',
 'V198',
 'V199',
 'V200',
 'V201',
 'V202',
 'V203',
 'V204',
 'V205',
 'V206',
 'V207',
 'V208',
 'V209',
 'V210',
 'V211',
 'V212',
 'V213',
 'V214',
 'V215',
 'V216',
 'V217',
 'V218',
 'V219',
 'V220',
 'V221',
 'V222',
 'V223',
 'V224',
 'V225',
 'V226',
 'V227',
 'V228',
 'V229',
 'V230',
 'V231',
 'V232',
 'V233',
 'V234',
 'V235',
 'V236',
 'V237',
 'V238',
 'V239',
 'V240',
 'V241',
 'V242',
 'V243',
 'V244',
 'V245',
 'V246',
 'V247',
 'V248',
 'V249',
 'V250',
 'V251',
 'V252',
 'V253',
 'V254',
 'V255',
 'V256',
 'V257',
 'V258',
 'V259',
 'V260',
 'V261',
 'V262',
 'V263',
 'V264',
 'V265',
 'V266',
 'V267',
 'V268',
 'V269',
 'V270',
 'V271',
 'V272',
 'V273',
 'V274',
 'V275',
 'V276',
 'V277',
 'V278',
 'V322',
 'V323',
 'V324',
 'V325',
 'V326',
 'V327',
 'V328',
 'V329',
 'V330',
 'V331',
 'V332',
 'V333',
 'V334',
 'V335',
 'V336',
 'V337',
 'V338',
 'V339',
 'id_01',
 'id_02',
 'id_03',
 'id_04',
 'id_05',
 'id_06',
 'id_07',
 'id_08',
 'id_09',
 'id_10',
 'id_11',
 'id_12',
 'id_13',
 'id_14',
 'id_15',
 'id_16',
 'id_17',
 'id_18',
 'id_19',
 'id_20',
 'id_21',
 'id_22',
 'id_23',
 'id_24',
 'id_25',
 'id_26',
 'id_27',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_32',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo']

In [8]:
print(f"Number of columns being dropped: {len(columns_drop)}")
df = df.drop(columns = columns_drop)
print(f"Final shape of dataset after the columns were dropped : {df.shape}")

Number of columns being dropped: 214
Final shape of dataset after the columns were dropped : (590540, 220)

Clipping Outliers

In [9]:
df['TransactionAmt'] = df['TransactionAmt'].clip(upper = 2769.81)

In [10]:
print(f"Shape : {df.shape}")
print(f"Fraud Rate: {df['isFraud'].mean()*100:.2f} %")

Shape : (590540, 220)
Fraud Rate: 3.50 %

Checking for other missing values

In [11]:
missing_value = df.isnull().sum()
missing_value

TransactionID      0
isFraud            0
TransactionDT      0
TransactionAmt     0
ProductCD          0
                  ..
V317              12
V318              12
V319              12
V320              12
V321              12
Length: 220, dtype: int64

In [12]:
cols_missing_value = missing_value[missing_value > 0].index.tolist()
print(f"Number of columns with missing value: {len(cols_missing_value)}")
cols_missing_value

Number of columns with missing value: 200

['card2',
 'card3',
 'card4',
 'card5',
 'card6',
 'addr1',
 'addr2',
 'P_emaildomain',
 'D1',
 'D2',
 'D3',
 'D4',
 'D10',
 'D11',
 'D15',
 'M1',
 'M2',
 'M3',
 'M4',
 'M6',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'V29',
 'V30',
 'V31',
 'V32',
 'V33',
 'V34',
 'V35',
 'V36',
 'V37',
 'V38',
 'V39',
 'V40',
 'V41',
 'V42',
 'V43',
 'V44',
 'V45',
 'V46',
 'V47',
 'V48',
 'V49',
 'V50',
 'V51',
 'V52',
 'V53',
 'V54',
 'V55',
 'V56',
 'V57',
 'V58',
 'V59',
 'V60',
 'V61',
 'V62',
 'V63',
 'V64',
 'V65',
 'V66',
 'V67',
 'V68',
 'V69',
 'V70',
 'V71',
 'V72',
 'V73',
 'V74',
 'V75',
 'V76',
 'V77',
 'V78',
 'V79',
 'V80',
 'V81',
 'V82',
 'V83',
 'V84',
 'V85',
 'V86',
 'V87',
 'V88',
 'V89',
 'V90',
 'V91',
 'V92',
 'V93',
 'V94',
 'V95',
 'V96',
 'V97',
 'V98',
 'V99',
 'V100',
 'V101',
 'V102',
 'V103',
 'V104',
 'V105',
 'V106',
 'V107',
 'V108',
 'V109',
 'V110',
 'V111',
 'V112',
 'V113',
 'V114',
 'V115',
 'V116',
 'V117',
 'V118',
 'V119',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V126',
 'V127',
 'V128',
 'V129',
 'V130',
 'V131',
 'V132',
 'V133',
 'V134',
 'V135',
 'V136',
 'V137',
 'V279',
 'V280',
 'V281',
 'V282',
 'V283',
 'V284',
 'V285',
 'V286',
 'V287',
 'V288',
 'V289',
 'V290',
 'V291',
 'V292',
 'V293',
 'V294',
 'V295',
 'V296',
 'V297',
 'V298',
 'V299',
 'V300',
 'V301',
 'V302',
 'V303',
 'V304',
 'V305',
 'V306',
 'V307',
 'V308',
 'V309',
 'V310',
 'V311',
 'V312',
 'V313',
 'V314',
 'V315',
 'V316',
 'V317',
 'V318',
 'V319',
 'V320',
 'V321']

In [13]:
missing_mean = df.isnull().mean()
missing_mean = missing_mean.sort_values(ascending = False)
missing_mean

M4                0.476588
D2                0.475492
V9                0.472935
V10               0.472935
V5                0.472935
                    ...
C10               0.000000
TransactionAmt    0.000000
TransactionDT     0.000000
isFraud           0.000000
TransactionID     0.000000
Length: 220, dtype: float64

In [14]:
numerical_col_missing = df[missing_mean.index].select_dtypes(include = np.number).columns.tolist()
categorical_col_missing = df[missing_mean.index].select_dtypes(include = 'object').columns.tolist()

print(f"Number of numerical columns: {len(numerical_col_missing)}")
print(f"Number of categorical columns: {len(categorical_col_missing)}")

Number of numerical columns: 211
Number of categorical columns: 9

Forming Imputation Strategy

1. Categorical Columns : Fill with 'Unknown'
2. D-Columns (Time deltas) : Fill with -999 (They represent days between previous transactions , Missing values likely indicate unavailable historical information)
3. M- Columns (Match Flags , Match : name on cards/address) : Fill with Missing
4. V-Columns : Vesta Engineered features , already engineered features , hence cant do median imputation , would have to replace by -999

In [15]:
categorical_col_missing

['M4', 'M1', 'M3', 'M2', 'M6', 'P_emaildomain', 'card4', 'card6', 'ProductCD']

In [19]:
numerical_col_missing

['D2',
 'V9',
 'V10',
 'V5',
 'V4',
 'V2',
 'V1',
 'D11',
 'V3',
 'V11',
 'V8',
 'V7',
 'V6',
 'D3',
 'V48',
 'V44',
 'V43',
 'V42',
 'V41',
 'V40',
 'V47',
 'V46',
 'V45',
 'V51',
 'V52',
 'V38',
 'V37',
 'V39',
 'V50',
 'V35',
 'V36',
 'V49',
 'D4',
 'V81',
 'V93',
 'V94',
 'V91',
 'V92',
 'V85',
 'V86',
 'V87',
 'V88',
 'V89',
 'V90',
 'V75',
 'V76',
 'V83',
 'V84',
 'V82',
 'V77',
 'V80',
 'V79',
 'V78',
 'D15',
 'V56',
 'V55',
 'V58',
 'V57',
 'V54',
 'V53',
 'V67',
 'V68',
 'V65',
 'V66',
 'V63',
 'V64',
 'V70',
 'V69',
 'V71',
 'V72',
 'V60',
 'V59',
 'V73',
 'V74',
 'V62',
 'V61',
 'V30',
 'V29',
 'V24',
 'V23',
 'V33',
 'V34',
 'V12',
 'V13',
 'V14',
 'V20',
 'V17',
 'V18',
 'V15',
 'V16',
 'V19',
 'V26',
 'V21',
 'V22',
 'V32',
 'V31',
 'V28',
 'V27',
 'V25',
 'D10',
 'addr2',
 'addr1',
 'card2',
 'card5',
 'card3',
 'D1',
 'V314',
 'V313',
 'V296',
 'V301',
 'V300',
 'V281',
 'V289',
 'V288',
 'V283',
 'V282',
 'V315',
 'V115',
 'V114',
 'V113',
 'V116',
 'V111',
 'V110',
 'V109',
 'V108',
 'V107',
 'V106',
 'V126',
 'V125',
 'V117',
 'V119',
 'V118',
 'V132',
 'V131',
 'V130',
 'V129',
 'V112',
 'V105',
 'V103',
 'V104',
 'V101',
 'V102',
 'V95',
 'V96',
 'V97',
 'V98',
 'V99',
 'V100',
 'V137',
 'V136',
 'V127',
 'V120',
 'V128',
 'V133',
 'V135',
 'V134',
 'V121',
 'V122',
 'V123',
 'V124',
 'V286',
 'V287',
 'V284',
 'V285',
 'V305',
 'V304',
 'V303',
 'V306',
 'V279',
 'V280',
 'V293',
 'V290',
 'V297',
 'V295',
 'V299',
 'V298',
 'V302',
 'V294',
 'V292',
 'V291',
 'V312',
 'V311',
 'V316',
 'V317',
 'V309',
 'V310',
 'V308',
 'V307',
 'V318',
 'V319',
 'V320',
 'V321',
 'card1',
 'C1',
 'C2',
 'C11',
 'C12',
 'C13',
 'C14',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'TransactionAmt',
 'TransactionDT',
 'isFraud',
 'TransactionID']

In [20]:
# 1. Filling M columns missing values with 'missing'
m_cols = []
for c in categorical_col_missing:
    if c.startswith('M'):
        m_cols.append(c)

for col in m_cols:
    df[col] = df[col].fillna('missing')

# 2. Remaining categorical columns missing values filled with unkown
not_m_cols = []
for c in categorical_col_missing:
    if not c.startswith('M'):
        not_m_cols.append(c)

for col in not_m_cols:
    df[col] = df[col].fillna('unknown')

# 3. All numeric columns being filled with -999
for col in numerical_col_missing:
    df[col] = df[col].fillna(-999)

In [22]:
df.isnull().sum().sum()

np.int64(0)

Creating hour column

In [25]:
# Suppose a transaction occurs at TransactionDT = 100000 (this much time after a reference point)
# So convert to hours = 100000 / 3600 = 27.78 and then take modulo of 24 = 27.78 % 24 = 3.78
# So transaction occurred around 3:47 AM relative to the reference date

df['hour'] = (df['TransactionDT'] / 3600) % 24  

# Cyclic Encoding for Linear models and Autoencoder
df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

df.drop(columns = 'TransactionDT' , inplace = True)
df

,TransactionID,isFraud,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V315,V316,V317,V318,V319,V320,V321,hour,hour_sin,hour_cos
0,2987000,0,68.50,W,13926,-999.0,150.0,discover,142.0,credit,...,0.000000,0.0,117.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
1,2987001,0,29.00,W,2755,404.0,150.0,mastercard,102.0,credit,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000278,0.000073,1.000000
2,2987002,0,59.00,W,4663,490.0,150.0,visa,166.0,debit,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.019167,0.005018,0.999987
3,2987003,0,50.00,W,18132,567.0,150.0,mastercard,117.0,debit,...,0.000000,50.0,1404.0,790.0,0.000000,0.000000,0.000000,0.027500,0.007199,0.999974
4,2987004,0,50.00,H,4497,514.0,150.0,mastercard,102.0,credit,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.029444,0.007708,0.999970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,3577535,0,49.00,W,6550,-999.0,150.0,visa,226.0,debit,...,47.950001,0.0,0.0,0.0,0.000000,0.000000,0.000000,23.957500,-0.011126,0.999938
590536,3577536,0,39.50,W,10444,225.0,150.0,mastercard,224.0,debit,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,23.958056,-0.010981,0.999940
590537,3577537,0,30.95,W,12037,595.0,150.0,mastercard,224.0,debit,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,23.966389,-0.008799,0.999961
590538,3577538,0,117.00,W,7826,481.0,150.0,mastercard,224.0,debit,...,317.500000,0.0,2234.0,0.0,0.000000,0.000000,0.000000,23.968889,-0.008145,0.999967
590539,3577539,0,279.95,W,15066,170.0,150.0,mastercard,102.0,credit,...,0.000000,0.0,0.0,0.0,279.950012,279.950012,279.950012,23.980833,-0.005018,0.999987

Amount Features (Creation of Composite card and Amount z-score per unique card)